# Generated by Django 4.2.25 on 2025-10-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
