# Generated by Django 4.2.25 on 2025-11-05 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management_system_app', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(help_text='Select the student assigned to this task.', related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
